# Generated by Django 2.1.3 on 2019-02-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_auto_20190216_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choce_text',
            new_name='choice_text',
        ),
    ]
